# Generated by Django 3.2 on 2023-07-21 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_desa_jarakan', '0003_alter_homecardimageplugin_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecardimageplugin',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
