# Generated by Django 3.2 on 2023-07-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('profil_desa_jarakan', '0006_alter_homecardimageplugin_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKMPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profil_desa_jarakan_umkmplugin', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
