# Generated by Django 3.2 on 2023-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_desa_jarakan', '0007_umkmplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkmplugin',
            name='link_ecommerce',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
