# Generated by Django 3.2 on 2023-07-29 08:58

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('profil_desa_jarakan', '0008_umkmplugin_link_ecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkmplugin',
            name='placeholder_field',
            field=cms.models.fields.PlaceholderField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='placeholder slot name', to='cms.placeholder'),
        ),
    ]
