# Generated by Django 3.2 on 2023-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_desa_jarakan', '0016_homeberitacardplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecardimagewideplugin',
            name='redirect_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
