# Generated by Django 3.2 on 2023-07-15 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tanggal', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homecardimageplugin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homecardimageplugin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homecardimageplugin',
            name='tanggal',
        ),
        migrations.RemoveField(
            model_name='homecardimageplugin',
            name='title',
        ),
        migrations.AddField(
            model_name='homecardimageplugin',
            name='home_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls_cms_integration.homecardimage'),
        ),
    ]
