# Generated by Django 3.2 on 2023-07-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0002_acardplugin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acardplugin',
            name='image',
        ),
    ]
