# Generated by Django 3.2 on 2023-07-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0002_auto_20230715_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecardimageplugin',
            name='home_card_image',
        ),
        migrations.AddField(
            model_name='homecardimageplugin',
            name='description',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecardimageplugin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homecardimageplugin',
            name='tanggal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecardimageplugin',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomeCardImage',
        ),
    ]
