# Generated by Django 3.2 on 2023-07-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0003_auto_20230715_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tanggal', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
