# Generated by Django 3.2 on 2023-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0003_remove_acardplugin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='acardplugin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
