# Generated by Django 3.2 on 2023-07-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0005_auto_20230714_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecardimageplugin',
            old_name='title1',
            new_name='title',
        ),
    ]
