# Generated by Django 3.2 on 2023-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cms_integration', '0006_rename_title1_homecardimageplugin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecardimageplugin',
            name='description',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
