# Generated by Django 3.2 on 2023-07-14 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('polls_cms_integration', '0008_homecardimageplugin_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PejabatCardPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='polls_cms_integration_pejabatcardplugin', serialize=False, to='cms.cmsplugin')),
                ('tingkat_jabatan', models.CharField(max_length=100)),
                ('nama_pejabat', models.CharField(max_length=100)),
                ('tanggal_mulai_menjabat', models.DateField(default=datetime.date.today)),
                ('tanggal_akhir_jabatan', models.DateField(default=datetime.date.today)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
